apiVersion: v1
kind: ReplicationController
metadata:
    name: repli
spec:
    replicas: 3
    selector:
      app: hello
    template:
      metadata:
        name: "POD"
        labels:
          app: hello
      spec:
        containers:
        - name: "yup"
          image: "vimal13/apache-webserver-php" 