apiVersion: v1
kind: Pod
metadata:
    name: "wpdb"
    labels:
      app: database

spec:
    containers:
    - name: "wpdb"
      image: "mysql:5.7"
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: pass
      - name: MYSQL_USER
        value: yogesh
      - name: MYSQL_PASS
        value: redat
      - name: MYSQL_DATABASE
        value: WPDB