apiVersion: v1
kind: ReplicationController
metadata:
    name: myrc1
spec:
    replicas: 4
    selector:
      app: Hello
    template:
      metadata:
        name: "mypod2"
        labels:
          app: Hello
      spec:
        containers:
        - name: "mycontainer1"
          image: "vimal13/apache-webserver-php"     